default: &default
  adapter: postgresql
  encoding: unicode
  pool:  5
  username: postgres
  password: postgres

development:
  <<: *default
  database: myprotfolio_dev

test:
  <<: *default
  database: myprotfolio_dev_test

production:
  <<: *default
  database: myprotfolio_development
